add_library(kernelmgr_core STATIC
        KernelArchive.cpp
        KernelArchive.h
        BuildConfig.cpp
        BuildConfig.h
        Configuration.cpp
        Configuration.h
        Kernel.cpp
        Kernel.h
        Log.cpp
        Log.h
        Command.cpp
        Command.h
        Download.cpp
        Download.h
        Elevation.cpp
        Elevation.h
        Make.h
        Process.cpp
        Process.h
        SystemInfo.h
        Progress.cpp
        Progress.h
        workflow/BuildTask.cpp
        workflow/BuildTask.h
        workflow/CleanTask.cpp
        workflow/CleanTask.h
        workflow/ConfigureTask.cpp
        workflow/ConfigureTask.h
        workflow/DownloadTask.cpp
        workflow/DownloadTask.h
        workflow/ExtractTask.cpp
        workflow/ExtractTask.h
        workflow/InstallTask.cpp
        workflow/InstallTask.h
        workflow/PatchTask.cpp
        workflow/PatchTask.h
        workflow/ProcessTask.cpp
        workflow/ProcessTask.h
        workflow/PullTask.cpp
        workflow/PullTask.h
        workflow/SignTask.cpp
        workflow/SignTask.h
        workflow/Task.h
        workflow/Workflow.cpp
        workflow/Workflow.h
        workflow/WorkflowFactory.cpp
        workflow/WorkflowFactory.h)

target_compile_options(kernelmgr_core PRIVATE ${COMPILE_FLAGS})

target_link_libraries(kernelmgr_core
        PUBLIC
        kernelmgr_sanitizers
        PRIVATE
        yyjson
        -larchive
        -lcurl
        -lutil)
